name: Build and Test the Digibank
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  repository_dispatch:
    types: [trigger-tests]
    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
      SUT:
        description: 'SUT (IP) to run tests against'
        type: string
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Check IP
        run: echo ${{ github.event.api_payload.sut }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install

      - name: run the tests
        run: SUT="http://${{ github.event.api_payload.sut }}:8080/digibank/login" npx playwright test
             
      - if: always()
        uses: actions/upload-artifact@master
        with:
          name: test-report.html
          path: ./playwright-report/index.html
      
      - if: always()
        name: Test Report Link
        run: echo "Test Report Link - http://${{ github.event.api_payload.sut }}/report/playwright-report/" >> $GITHUB_STEP_SUMMARY

