name: Build and Test the Digibank
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true 
      SUT:
        description: 'SUT (IP) to run tests against'
        type: string
        required: true 

env:
  SUT: $ {{ inputs.SUT }}

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install

      - name: PRINTENV
        run: printenv

      - name: run the tests
        if: ${{ inputs.SUT }}
        run: npx playwright test

      # - name: upload test reports
        # report ./playwright-report/index.html
